import "./globals.css";


export const metadata = {
  title: "Formulario de Registro",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-sans font-bold">
        {children}
      </body>
    </html>
  );
}
